name: build
on: 
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      # - name: NeoForge Kits Cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/Kits
      #     key: ${{ runner.os }}-Kits-${{ hashFiles('snapshot_version') }}
      #     restore-keys: |
      #       ${{ runner.os }}-Kits-
      - name: Compile NeoForge snapshot
        run: ./build-and-publish.sh
